[project]
name = "inf-typed-graph"
version = "0.1.0"
description = "Python base package for typed graph"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datalog>=0.7.8",
    "problog>=2.2.10",
    "pydantic>=2.13.4",
    "rg>=0.0.76",
    "ruff>=0.15.21",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "mypy>=2.3.0",
    "pytest>=9.1.1",
]

[tool.black]
target-version = ["py312"]

[tool.pytest.ini_options]
pythonpath = ["."]
