"""Serialize a graph (a collection of instances) to runnable Python source.

Executing the emitted source rebuilds an equal graph -- deserialization is just
`exec`, no parser. The output is a flat, topologically ordered program: one
variable per instance (named from its id), with instance-valued fields
(`subject` / `object_`) referenced by variable, so shared nodes and higher-order
statements keep their structure.

Constraints (all satisfied by base.py / example.py today):

- Every entity/predicate class must live in an importable module (not __main__
  or a test-local scope), so the generated `from ... import ...` can name it.
- Every non-instance field value must round-trip through `repr` -- str, Literal,
  and nested frozen models like Provenance all do. A field holding, say, a
  datetime or a bare collection of instances would need special handling.
- The instance graph is a DAG (a frozen statement cannot be built before its
  subject/object exist), so topological ordering always succeeds.
"""

from __future__ import annotations

import importlib
import keyword
import re
from collections.abc import Iterable
from typing import Any

try:
    import black as _black

    _BLACK_MODE = _black.Mode(target_versions={_black.TargetVersion.PY312})

    def _fmt(src: str) -> str:
        return _black.format_str(src, mode=_BLACK_MODE)

except ImportError:

    def _fmt(src: str) -> str:  # type: ignore[misc]
        return src

from pydantic import BaseModel

from base import Instance

_GENERATED_HEADER = "# Generated by serialize.to_python; do not edit by hand."
_EMITTED_INSTANCES = "__instances_by_id__"


def _instance_deps(inst: Instance) -> list[Instance]:
    """The instances `inst` references through its fields (subject / object_)."""
    deps: list[Instance] = []
    for name in type(inst).model_fields:
        value = getattr(inst, name)
        if isinstance(value, Instance):
            deps.append(value)
    return deps


def _closure_topo(roots: Iterable[Instance]) -> list[Instance]:
    """All instances reachable from `roots`, dependencies first, deduped by id."""
    by_id: dict[str, Instance] = {}
    order: list[Instance] = []

    def visit(inst: Instance) -> None:
        existing = by_id.get(inst.id)
        if existing is not None:
            if existing != inst:
                raise ValueError(
                    f"two distinct instances share id {inst.id!r}; ids must be unique"
                )
            return
        by_id[inst.id] = inst
        for dep in _instance_deps(inst):
            visit(dep)
        order.append(inst)

    for root in roots:
        visit(root)
    return order


def _var_names(
    order: list[Instance], reserved: set[str] | None = None
) -> dict[str, str]:
    """A unique, valid Python identifier for each instance id."""
    used = set() if reserved is None else set(reserved)
    names: dict[str, str] = {}
    for inst in order:
        base = re.sub(r"\W", "_", inst.id)
        if not base or not (base[0].isalpha() or base[0] == "_"):
            base = "_" + base
        if keyword.iskeyword(base):
            base += "_"
        name = base
        n = 2
        while name in used:
            name = f"{base}_{n}"
            n += 1
        used.add(name)
        names[inst.id] = name
    return names


def _render(value: Any, names: dict[str, str]) -> str:
    """A source expression for one field value: a variable reference if it is an
    instance, else its repr (valid source for str / Literal / frozen sub-models)."""
    if isinstance(value, Instance):
        return names[value.id]
    return repr(value)


def _embedded_non_instance_models(value: Any) -> list[BaseModel]:
    """All non-instance BaseModel values nested inside `value`."""
    if isinstance(value, Instance):
        return []
    if isinstance(value, BaseModel):
        return [value]
    if isinstance(value, (tuple, list, set, frozenset)):
        embedded: list[BaseModel] = []
        for item in value:
            embedded.extend(_embedded_non_instance_models(item))
        return embedded
    if isinstance(value, dict):
        embedded = []
        for item in value.values():
            embedded.extend(_embedded_non_instance_models(item))
        return embedded
    return []


def _render_emitted_instances(order: list[Instance], names: dict[str, str]) -> str:
    """A dict literal body mapping instance ids to emitted variables.

    The ids use repr(), so punctuation and quotes remain valid Python string
    literals in the generated source.
    """
    return ", ".join(f"{inst.id!r}: {names[inst.id]}" for inst in order)


def to_python(instances: Iterable[Instance]) -> str:
    """Serialize the transitive closure of `instances` to a runnable Python
    program that rebuilds an equal graph when executed."""
    order = _closure_topo(instances)

    imports: dict[str, set[str]] = {}

    def note(t: type) -> None:
        if t.__module__ == "__main__":
            raise ValueError(
                f"{t.__name__} must be importable as a module attribute, not from "
                "__main__"
            )
        try:
            module = importlib.import_module(t.__module__)
        except ImportError as exc:
            raise ValueError(
                f"{t.__name__} must live in an importable module, got "
                f"{t.__module__!r}"
            ) from exc
        if getattr(module, t.__name__, None) is not t:
            raise ValueError(
                f"{t.__name__} must be importable as a module attribute from "
                f"{t.__module__!r}"
            )
        imports.setdefault(t.__module__, set()).add(t.__name__)

    for inst in order:
        note(type(inst))
        for fname in type(inst).model_fields:
            value = getattr(inst, fname)
            # A non-instance sub-model (e.g. Provenance) may appear directly or
            # inside a collection; it is reconstructed by repr, so its class
            # must be imported too.
            for model in _embedded_non_instance_models(value):
                note(type(model))

    reserved_names = {
        name for class_names in imports.values() for name in class_names
    } | {_EMITTED_INSTANCES}
    names = _var_names(order, reserved=reserved_names)
    import_lines = [
        f"from {module} import {', '.join(sorted(imports[module]))}"
        for module in sorted(imports)
    ]

    assign_lines = []
    for inst in order:
        args = ", ".join(
            f"{fname}={_render(getattr(inst, fname), names)}"
            for fname in type(inst).model_fields
        )
        assign_lines.append(f"{names[inst.id]} = {type(inst).__name__}({args})")

    src = (
        f"{_GENERATED_HEADER}\n"
        + "\n".join(import_lines)
        + "\n\n"
        + "\n".join(assign_lines)
        + f"\n\n{_EMITTED_INSTANCES} = {{{_render_emitted_instances(order, names)}}}\n"
    )
    return _fmt(src)


def from_python(source: str) -> list[Instance]:
    """Execute `source` and return the instances it binds. Inverse of `to_python`
    (the deserializer is just the Python interpreter)."""
    namespace: dict[str, Any] = {}
    exec(source, namespace)  # noqa: S102 -- trusted, self-generated source
    emitted = namespace.get(_EMITTED_INSTANCES)
    if not isinstance(emitted, dict) or not all(
        isinstance(v, Instance) for v in emitted.values()
    ):
        raise ValueError("source did not define the emitted instance registry")
    return list(emitted.values())
