"""ProbLog adapter for optional probabilistic evaluation over the typed graph.

This module keeps probabilistic inference separate from the core Boolean
engine. It emits a ProbLog program from asserted graph facts and can evaluate
that program when the optional ``problog`` package is available.
"""

from __future__ import annotations

import importlib
import json
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any, Literal, Protocol, TypeGuard

from base import BaseStatement
from graph import Graph


class ProbLogUnavailableError(RuntimeError):
    """Raised when ProbLog execution is requested but the package is unavailable."""


class ProbLogEvaluator(Protocol):
    """Callable interface for evaluating ProbLog source to marginal probabilities."""

    def __call__(self, source: str) -> Mapping[str, float]: ...


@dataclass(frozen=True)
class ProbLogProgram:
    """Rendered ProbLog source and the query symbol -> external id mapping."""

    source: str
    query_symbols: dict[str, str]


def _camel_to_snake(name: str) -> str:
    return re.sub(r"(?<!^)([A-Z])", r"_\1", name).lower()


def _quote(term: str) -> str:
    return json.dumps(term)


def _is_asserted_statement(inst: object) -> TypeGuard[BaseStatement[Any, Any]]:
    return isinstance(inst, BaseStatement) and inst.truth_status == "asserted_true"


def _iter_asserted_statements(graph: Graph) -> list[BaseStatement[Any, Any]]:
    stmts: list[BaseStatement[Any, Any]] = []
    for inst in graph.by_id.values():
        if not _is_asserted_statement(inst):
            continue
        stmts.append(inst)
    return sorted(stmts, key=lambda stmt: stmt.id)


def emit_asserted_facts(graph: Graph) -> list[str]:
    """Emit deterministic ProbLog facts for asserted graph statements."""
    lines: list[str] = []
    for stmt in _iter_asserted_statements(graph):
        pred = _camel_to_snake(type(stmt).__name__)
        lines.append(f"{pred}({_quote(stmt.subject.id)}, {_quote(stmt.object_.id)}).")
    return lines


def build_candidate_place_program(
    graph: Graph,
    *,
    object_id: str,
    candidate_place_ids: Sequence[str],
    query_predicate: str = "physically_in",
    query_arity: Literal[1, 2] = 2,
    primitive_lines: Sequence[str] = (),
    evidence_lines: Sequence[str] = (),
) -> ProbLogProgram:
    """Build a ProbLog program that queries candidate places for one object."""
    lines: list[str] = [
        "% Generated by sherlock.problog_adapter; optional probabilistic layer.",
        *primitive_lines,
        *emit_asserted_facts(graph),
        "",
        (
            "physically_in(Object, Place) :- "
            "possesses(Person, Object), "
            "involves(Event, Person), "
            "occurred_at(Event, Moment), "
            "associated_with(Person, Place), "
            "happened_in(Event, Place)."
        ),
    ]

    query_symbols: dict[str, str] = {}
    for index, place_id in enumerate(candidate_place_ids, start=1):
        symbol = f"candidate_place_{index}"
        if query_arity == 1:
            query_atom = f"{query_predicate}({_quote(place_id)})"
        else:
            query_atom = f"{query_predicate}({_quote(object_id)}, {_quote(place_id)})"
        lines.append(f"{symbol} :- {query_atom}.")
        lines.append(f"query({symbol}).")
        query_symbols[symbol] = place_id

    for raw_line in evidence_lines:
        line = raw_line.strip()
        if not line:
            continue
        if not line.endswith("."):
            line = line + "."
        lines.append(line)

    return ProbLogProgram(source="\n".join(lines) + "\n", query_symbols=query_symbols)


def _default_problog_evaluator(source: str) -> Mapping[str, float]:
    """Run ProbLog if installed, returning stringified query keys."""
    try:
        problog_mod = importlib.import_module("problog")
        program_mod = importlib.import_module("problog.program")
    except ImportError as exc:
        raise ProbLogUnavailableError(
            "ProbLog is not installed. Install it to execute probabilistic "
            "evaluation, or pass a custom evaluator."
        ) from exc

    get_evaluatable = getattr(problog_mod, "get_evaluatable")
    prolog_string = getattr(program_mod, "PrologString")

    result = get_evaluatable().create_from(prolog_string(source)).evaluate()
    return {str(term): float(prob) for term, prob in result.items()}


def evaluate_program(
    source: str,
    *,
    evaluator: ProbLogEvaluator | None = None,
) -> dict[str, float]:
    """Evaluate ProbLog source and return query marginals by query symbol."""
    resolved = evaluator if evaluator is not None else _default_problog_evaluator
    return dict(resolved(source))


def evaluate_candidate_place_marginals(
    graph: Graph,
    *,
    object_id: str,
    candidate_place_ids: Sequence[str],
    query_predicate: str = "physically_in",
    query_arity: Literal[1, 2] = 2,
    primitive_lines: Sequence[str] = (),
    evidence_lines: Sequence[str] = (),
    evaluator: ProbLogEvaluator | None = None,
) -> tuple[ProbLogProgram, dict[str, float]]:
    """Build and evaluate candidate place queries for one object."""
    program = build_candidate_place_program(
        graph,
        object_id=object_id,
        candidate_place_ids=candidate_place_ids,
        query_predicate=query_predicate,
        query_arity=query_arity,
        primitive_lines=primitive_lines,
        evidence_lines=evidence_lines,
    )
    query_result = evaluate_program(program.source, evaluator=evaluator)
    marginals = {
        place_id: float(query_result.get(symbol, 0.0))
        for symbol, place_id in program.query_symbols.items()
    }
    return program, marginals
